### PR TITLE
patch default conda-exe on arm64 and use micromamba

### PR DESCRIPTION
**Pull request by jaimergp**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

@isuruf - would this be a valid workaround for https://github.com/conda-forge/conda-standalone-feedstock/pull/10 ?

### CODE REVIEW

**Comment by isuruf** [comment]
I don't like the patching. I'd rather we make a symlink from micromamba to the place where constructor expects it to be.
Also installing micromamba from conda is problematic due to a bug in path replacement.

**Comment by jaimergp** [comment]
> I'd rather we make a symlink from micromamba to the place where constructor expects it to be.

I can try that.

> Also installing micromamba from conda is problematic due to a bug in path replacement.

Can we add the micromamba binary tarball to the sources and vendor it with a different name? Or build with out it and error out with a message that lets the user know they need to install `micromamba` manually?

**Comment by isuruf** [comment]
> Can we add the micromamba binary tarball to the sources and vendor it with a different name? 

Sure. Make sure the copyrights/license texts are vendored too.

**Comment by jaimergp** [comment]
Hm, the py39 build fails with a solver conflict.

I also tried locally and [due to these checks](https://github.com/conda/constructor/blob/master/constructor/main.py#L224-L232), the symlink available at `$PREFIX/conda_standalone/conda.exe` is not used -- it errors out before getting to that part. So maybe we do need to patch the default setting for `--conda-exe`.

Thoughts?

**Comment by jaimergp** [comment]
Ping @isuruf :)

**Comment by jaimergp** [comment]
What if we just drop the `conda-standalone` dependency on osx-arm64 and let it error out with an informative message ("Please install conda-standalone or micromamba for cross-platform installers")? Alternatively, I can also send a PR to upstream so they try locate micromamba if conda-standalone was not found.

**Comment by jaimergp** [comment]
cc https://github.com/conda/constructor/issues/454

**Pull request closed without merging**
