### PR TITLE
Release 2.0.0

### PR DESCRIPTION
**Pull request by jakirkham**
Makes a few changes based on upstream. Also bumps the version to 2.0.0. Changelog follows.

```
2017-11-01   2.0.0:
-------------------
  * COMMON:
    - Add support for channel remapping
    - Make sure $PREFIX/envs is created by the installers
    - Fallback to cat if more is not available
    - Allow company name to be specified in construct.yaml
    - Add feature to check file duplicates across dists
    - Switch requirements to conda, ruamel_yaml
    - Add write_condarc option
    - Don't assume that channel keys will always be available
    - Parameterize installer name at various locations
    - Add support for pre-populating repodata cache
    - Introduce 'attempt_hardlinks' option
    - Copy pkgs to conda-bld (local) channel and test from there
    - Also add channels to .condarc
    - Remove urljoin import
    - Fix bug when downloading packages
    - Prefer conda via conda_interface instead of libconda
    - Add dry run option
    - Switch to setuptools
    - Remove eval from setup.py, use absolute paths
    - Add customization for welcome and header image texts
    - Add support and examples for aarch64
    - Add basic jinja2 support

  * NSIS:
    - Compute an approx. size for installation
    - Allow more than one vsXXXX runtime, but warn
    - Fix registry key handling
    - disallow installation when any files present in destination folder
    - Fix 'all users/just me' installation handling
    - Parameterize installation location for all users
    - Improve spaces/non-ascii/unicode character handling in nsis installer
    - Extract python and DLLs to %PREFIX%/%randomdir and ./.install from there
    - Fix several aspects of PATH env var management
    - Fix wording in Windows installer
    - Change AddToPath to not be the default
    - Add support for command line installation for Windows
    - Use ctypes for creating hard links on win
    - NSIS: Copy index cache directory
    - Fix issue when using conda to solve on windows
    - Add ability to make nsis verbose
    - Remove menus of all conda envs during uninstall
    - Add ability to provide defaults for custom options

  * PKG:
    - Add support for signing the pkg installer
    - Flip enable_{anywhere,localSystem}

  * SHELL:
    - Warn user if PYTHONPATH env var is set
    - Handle spaces in path to be patched
    - Compress non tarball files into preconda.tar.bz2
    - Standardise header.sh redirects
    - Add -t option to test the installer
    - Use getopt if available, fallback to getopts
    - Add more tests for RUNNING_SHELL
    - Remove bashisms from header.sh, using only POSIX, split tar and bunzip2
```

### CODE REVIEW

**Comment by jakirkham** [comment]
Any feedback from others?

cc @mbargull @mingwandroid @scopatz @megies

**Comment by jakirkham** [comment]
So running the tests have become more complicated now that `conda` is involved. This will likely require a strategy like that used in the `conda` recipe's tests added in PR ( https://github.com/conda-forge/conda-feedstock/pull/26 ). Am on the fence whether it is worth it here or whether we should return to just running `constructor --help`. Suggestions welcome.

**Comment by mbargull** [comment]
Being dependent on `conda` only makes it at most as "complicated" as the `conda-build` recipe which (apart from `conda-build`-specific stuff) doesn't seem to need anything out of the ordinary .

**Comment by jakirkham** [comment]
Ah ok. Thanks for the info, @mbargull. That's a much better situation than I was imagining.

Any thoughts on how we should tackle this? Skip the tests? Wait for a patch release? Patch it ourselves? Something else?

**Comment by mbargull** [comment]
There were a couple other tests that needed updates. I already issued PRs for those.
Since it only concern the tests, there usually needn't be a patch release. On the other hand for `constructor` we have the special case that the tests are actually part of the package itself as `constructor.tests`.
@mingwandroid: Will you release a `2.0.1` just because of fixed tests?

**Comment by mingwandroid** [comment]
I cannot get round to this in any short timeframe I do not think, sorry.

**Comment by mbargull** [comment]
No problem, thanks for the quick replay, @mingwandroid!

Then we can just patch, I'd suppose. IMHO, since `constructor` currently has a very small test suite, it wouldn't harm letting it run as a build test.

**Comment by jakirkham** [comment]
Is there a patch I should be grabbing from a PR somewhere?

**Comment by mbargull** [comment]
https://github.com/conda/constructor/pull/126
https://github.com/conda/constructor/pull/127
https://github.com/conda/constructor/pull/128

**Comment by jakirkham** [comment]
Looks like we need PR ( https://github.com/conda/constructor/pull/129 ) too. Tests just failed for me locally (on macOS) without it.

**Comment by jakirkham** [comment]
So this passes for me locally on macOS. We already know this passes on Linux. Have you already tested this on Windows, @mbargull? If so, I think we should be good here once CIs verify these results.

**Comment by mbargull** [comment]
No, haven't tested on Windows, only on Linux. Would need to fire up an old VM for that 🙈

**Comment by jakirkham** [comment]
np. Happy to wait for the CIs. Just was thinking you were a Windows user. 😄

**Comment by mbargull** [comment]
Once upon a time I was 😝.
But yes, once CIs are green, we're good to go, LGTM.

**Comment by jakirkham** [comment]
Thanks everyone! Should be generating some releases shortly.

**Pull request merged**
