### PR TITLE
Update sha

### PR DESCRIPTION
**Pull request by hmaarrfk**
Not sure how it changed

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jschueller** [comment]
so it was force-pushed ?

**Comment by hmaarrfk** [comment]
@mcg1969 do you know why the SHA of 3.2.1 might have changed?

**Comment by mcg1969** [comment]
Sorry for the confusion folks. There was an error in the CI around documentation building. I made corrections to that, and because the package itself did not change, I moved the tag to trigger a new tagged build. I did not appreciate these consequences.￼￼

**Comment by jakirkham** [comment]
GitHub autogenerates these as well, which means they can change if the archive generation process changes.

**Pull request merged**
