### PR TITLE
1.6.0

### PR DESCRIPTION
**Pull request by scopatz**
Actually updates to 1.6.0.  Includes #8

### CODE REVIEW

**Comment by jakirkham** [comment]
As noted in PR ( https://github.com/conda-forge/constructor-feedstock/pull/8 ) by @mbargull in this [comment]( https://github.com/conda-forge/constructor-feedstock/pull/8#issuecomment-311404956 ), it appears that this tag is not on `master`. Not sure if we should be releasing it or if we should go with `1.5.5` instead.

**Comment by jakirkham** [comment]
Any thoughts on this @mingwandroid?

**Comment by scopatz** [comment]
@jakirkham why is it a big deal that the tag contains commits that aren't on master? This is what they decided to release. Is there an issue somewhere saying that was an error?

**Comment by mbargull** [comment]
See the associated closed PR: https://github.com/conda/constructor/pull/71
That PR is from 2017-04-11 and includes the following statements:
> I need to do some more work on this

> .. however I need to revise this part for macOS before it's ready for review, so I'll close the issue for now, thanks.

Those make it likely that the tag wasn't meant as an "official" release (it hadn't been built for the `repo.continuum.io`, also). I'm not sure why that commit was tagged on 2017-04-18. @mingwandroid might be able to elaborate.

**Comment by mbargull** [comment]
FYI: Maybe we'll see a new release in the foreseeable future: https://github.com/conda/constructor/pull/124#issuecomment-340896619

**Comment by scopatz** [comment]
Oh, I see, that'd be great

**Comment by mingwandroid** [comment]
Our plan is to make a new significantly improved major release today and go through a proper release procedure this time!

**Comment by scopatz** [comment]
Sounds great! I will close this then.

**Comment by jakirkham** [comment]
Trying to release 2.0.0 with PR ( https://github.com/conda-forge/constructor-feedstock/pull/11 ). Feedback welcome.

**Pull request closed without merging**
