### PR TITLE
Backport fix from PR342

### PR DESCRIPTION
**Pull request by jschueller**
https://github.com/conda/constructor/pull/342

### CODE REVIEW

**Comment by jschueller** [comment]
@conda-forge/constructor I propose to merge this if a newer version is not in the making

**Comment by jschueller** [comment]
@conda-forge-admin please rerender

**Comment by hmaarrfk** [comment]
friendly ping.

**Comment by jschueller** [comment]
looks like a new release is not going to happen so soon (https://github.com/conda/constructor/issues/375)
@conda-forge/constructor please review

**Pull request closed without merging**
